import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Find the hidden code in 10 tries. Pick colours with a click or the keys 1–7 (each colour also has its own shape and number), Backspace removes one, Enter checks the row. A filled dot means a right colour in the right place; a ring means a right colour in the wrong place. Colours can repeat. Hard level: 5 pegs and 7 colours.",
    classic: "4 pegs · 6 colours",
    hard: "5 pegs · 7 colours",
    check: "Check",
    undo: "Remove",
    newGame: "New game",
    tries: "Try {n} of {tries}",
    won: "Cracked in {n} tries!",
    lost: "Out of tries. The code was:",
    feedback: "{exact} right place, {near} right colour only",
    color: "Colour {n}",
    legend: "dot = right place · ring = right colour",
  },
  fr: {
    help: "Trouvez le code caché en 10 essais. Choisissez les couleurs d'un clic ou avec les touches 1–7 (chaque couleur a aussi sa forme et son numéro), Retour arrière en retire une, Entrée vérifie la ligne. Un point plein : bonne couleur au bon endroit ; un anneau : bonne couleur au mauvais endroit. Les couleurs peuvent se répéter. Niveau difficile : 5 pions et 7 couleurs.",
    classic: "4 pions · 6 couleurs",
    hard: "5 pions · 7 couleurs",
    check: "Vérifier",
    undo: "Retirer",
    newGame: "Nouvelle partie",
    tries: "Essai {n} sur {tries}",
    won: "Code trouvé en {n} essais !",
    lost: "Plus d'essais. Le code était :",
    feedback: "{exact} bien placé(s), {near} bonne(s) couleur(s) seulement",
    color: "Couleur {n}",
    legend: "point = bien placé · anneau = bonne couleur",
  },
  rw: {
    help: "Shaka kode ihishe mu bigeragezo 10. Hitamo amabara ukanda cyangwa ukoresheje utubuto 1–7 (buri bara rifite n'ishusho n'umubare byaryo), Backspace ikuraho rimwe, Enter igenzura umurongo. Akadomo kuzuye bisobanura ibara ryiza ahantu heza; uruziga bisobanura ibara ryiza ahantu hatari ho. Amabara ashobora gusubiramo. Urwego rukomeye: udusimbo 5 n'amabara 7.",
    classic: "Udusimbo 4 · amabara 6",
    hard: "Udusimbo 5 · amabara 7",
    check: "Genzura",
    undo: "Kuraho",
    newGame: "Umukino mushya",
    tries: "Igerageza {n} kuri {tries}",
    won: "Wayivumbuye mu bigeragezo {n}!",
    lost: "Ibigeragezo birarangiye. Kode yari iyi:",
    feedback: "{exact} ahantu heza, {near} ibara ryiza gusa",
    color: "Ibara {n}",
    legend: "akadomo = ahantu heza · uruziga = ibara ryiza",
  },
};
