import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Pick a routine and follow the moves: each lasts 24 seconds, two minutes in all. Move gently and stop if anything hurts. It doesn't count towards your game time.",
    pick: "Pick a two-minute routine",
    start: "Start", next: "Next move", prev: "Previous move", stop: "Stop", again: "Another routine",
    done: "Done! Your body thanks you.",
    step: "Move {n} of {total}",
    desk: "Desk reset", tall: "Stand tall", eyes: "Rest your eyes", energy: "Energy boost", clap: "Clap & move", back: "Hands & back",
    desk1: "Sit tall. Slowly roll your shoulders backwards, then forwards.",
    desk2: "Tilt your head gently to the left, then to the right. Hold each side.",
    desk3: "Circle your wrists both ways, then spread and close your fingers.",
    desk4: "Turn your upper body to the left, hand on the chair back. Then the right.",
    desk5: "Lift your feet and draw slow circles with your ankles.",
    tall1: "Stand up, feet apart. Reach both arms high and stretch tall.",
    tall2: "Lean slowly to the left, then to the right, arms up.",
    tall3: "March on the spot, lifting your knees.",
    tall4: "Rise onto your toes, then lower slowly. Repeat.",
    tall5: "Shake out your arms and legs, loose and relaxed.",
    eyes1: "Look at something far away (out of a window if you can).",
    eyes2: "Blink slowly ten times.",
    eyes3: "Rub your palms warm and cover your closed eyes.",
    eyes4: "Look up, down, left and right, slowly, without moving your head.",
    eyes5: "Look far away again and breathe slowly.",
    energy1: "Arm circles: small, then big, forwards then backwards.",
    energy2: "Gentle half squats: bend your knees, back straight, and stand up.",
    energy3: "Step side to side, swinging your arms.",
    energy4: "Touch your right hand to your left knee, then left hand to right knee.",
    energy5: "Stand still, breathe in deeply and slowly breathe out.",
    clap1: "Clap a steady rhythm: clap, clap, rest.",
    clap2: "Clap, then tap your knees, then clap again.",
    clap3: "Step forward and clap, step back and clap.",
    clap4: "Clap above your head, then behind your back.",
    clap5: "Clap softer and softer until it is silent.",
    back1: "Push your palms together in front of your chest and hold.",
    back2: "Squeeze your shoulder blades together, then relax.",
    back3: "Hands on your knees, round your back like a hill, then arch it gently.",
    back4: "Lace your fingers behind your back and open your chest.",
    back5: "Reach down towards your toes, knees soft, then roll up slowly.",
  },
  fr: {
    help: "Choisissez une routine et suivez les mouvements : chacun dure 24 secondes, deux minutes en tout. Bougez doucement et arrêtez si quelque chose fait mal. Cela ne compte pas dans votre temps de jeu.",
    pick: "Choisissez une routine de deux minutes",
    start: "Commencer", next: "Mouvement suivant", prev: "Mouvement précédent", stop: "Arrêter", again: "Une autre routine",
    done: "Terminé ! Votre corps vous remercie.",
    step: "Mouvement {n} sur {total}",
    desk: "Pause bureau", tall: "Debout bien droit", eyes: "Reposer les yeux", energy: "Coup d'énergie", clap: "Taper et bouger", back: "Mains et dos",
    desk1: "Asseyez-vous droit. Roulez lentement les épaules vers l'arrière, puis vers l'avant.",
    desk2: "Inclinez doucement la tête à gauche, puis à droite. Tenez chaque côté.",
    desk3: "Tournez les poignets dans les deux sens, puis écartez et fermez les doigts.",
    desk4: "Tournez le haut du corps à gauche, main sur le dossier. Puis à droite.",
    desk5: "Levez les pieds et dessinez de lents cercles avec les chevilles.",
    tall1: "Levez-vous, pieds écartés. Tendez les bras vers le haut et grandissez-vous.",
    tall2: "Penchez-vous lentement à gauche, puis à droite, bras en l'air.",
    tall3: "Marchez sur place en levant les genoux.",
    tall4: "Montez sur la pointe des pieds, puis redescendez lentement. Répétez.",
    tall5: "Secouez les bras et les jambes, souples et détendus.",
    eyes1: "Regardez quelque chose de loin (par la fenêtre si possible).",
    eyes2: "Clignez lentement des yeux dix fois.",
    eyes3: "Frottez vos paumes pour les réchauffer et couvrez vos yeux fermés.",
    eyes4: "Regardez en haut, en bas, à gauche et à droite, lentement, sans bouger la tête.",
    eyes5: "Regardez de nouveau au loin et respirez lentement.",
    energy1: "Cercles de bras : petits puis grands, vers l'avant puis vers l'arrière.",
    energy2: "Demi-squats doux : pliez les genoux, dos droit, puis relevez-vous.",
    energy3: "Pas chassés de côté en balançant les bras.",
    energy4: "Main droite sur le genou gauche, puis main gauche sur le genou droit.",
    energy5: "Restez immobile, inspirez profondément et expirez lentement.",
    clap1: "Tapez un rythme régulier : clap, clap, pause.",
    clap2: "Tapez des mains, puis sur les genoux, puis de nouveau des mains.",
    clap3: "Un pas en avant et clap, un pas en arrière et clap.",
    clap4: "Tapez au-dessus de la tête, puis derrière le dos.",
    clap5: "Tapez de plus en plus doucement jusqu'au silence.",
    back1: "Pressez les paumes l'une contre l'autre devant la poitrine et tenez.",
    back2: "Serrez les omoplates, puis relâchez.",
    back3: "Mains sur les genoux, arrondissez le dos comme une colline, puis creusez-le doucement.",
    back4: "Croisez les doigts derrière le dos et ouvrez la poitrine.",
    back5: "Descendez vers les orteils, genoux souples, puis remontez lentement.",
  },
  rw: {
    help: "Hitamo urutonde ukurikire imyitozo: buri umwe umara amasegonda 24, iminota ibiri yose hamwe. Nyeganyega buhoro kandi uhagarare niba hari ikikubabaza. Ntibibarwa mu gihe cyawe cy'imikino.",
    pick: "Hitamo imyitozo y'iminota ibiri",
    start: "Tangira", next: "Umwitozo ukurikira", prev: "Umwitozo ubanza", stop: "Hagarika", again: "Indi myitozo",
    done: "Birarangiye! Umubiri wawe uragushimiye.",
    step: "Umwitozo {n} kuri {total}",
    desk: "Kuruhuka ku ntebe", tall: "Haguruka wemye", eyes: "Ruhura amaso", energy: "Ongera imbaraga", clap: "Koma amashyi unyeganyege", back: "Amaboko n'umugongo",
    desk1: "Icara wemye. Zengurutsa intugu buhoro inyuma, hanyuma imbere.",
    desk2: "Hengamiza umutwe buhoro ibumoso, hanyuma iburyo. Hagarara kuri buri ruhande.",
    desk3: "Zengurutsa intoki z'ukuboko impande zombi, hanyuma urambure kandi ufunge intoki.",
    desk4: "Hindukiza igice cyo hejuru cy'umubiri ibumoso, ukuboko ku ntebe. Hanyuma iburyo.",
    desk5: "Zamura ibirenge uzengurutse amaguru ku tugombambari buhoro.",
    tall1: "Haguruka, ibirenge bitandukanye. Zamura amaboko yombi hejuru wirambure.",
    tall2: "Hengama buhoro ibumoso, hanyuma iburyo, amaboko ari hejuru.",
    tall3: "Genda aho uri, uzamura amavi.",
    tall4: "Haguruka ku mano, hanyuma umanuke buhoro. Subiramo.",
    tall5: "Zunguza amaboko n'amaguru, woroshye kandi uruhutse.",
    eyes1: "Reba ikintu kiri kure (mu idirishya niba bishoboka).",
    eyes2: "Humbya buhoro inshuro icumi.",
    eyes3: "Sigasira ibiganza bishyuhe, hanyuma upfuke amaso ufunze.",
    eyes4: "Reba hejuru, hasi, ibumoso n'iburyo, buhoro, utanyeganyeza umutwe.",
    eyes5: "Ongera urebe kure kandi uhumeke buhoro.",
    energy1: "Zengurutsa amaboko: gato, hanyuma cyane, imbere hanyuma inyuma.",
    energy2: "Unama gato: hina amavi, umugongo wemye, hanyuma uhaguruke.",
    energy3: "Tera intambwe ku ruhande no ku rundi, uzunguza amaboko.",
    energy4: "Kora ku ivi ry'ibumoso ukoresheje ukuboko kw'iburyo, hanyuma ibinyuranye.",
    energy5: "Hagarara utuje, injiza umwuka cyane hanyuma uwusohore buhoro.",
    clap1: "Koma amashyi ku njyana imwe: koma, koma, ruhuka.",
    clap2: "Koma amashyi, ukubite ku mavi, wongere ukome amashyi.",
    clap3: "Tera intambwe imbere ukome amashyi, usubire inyuma ukome amashyi.",
    clap4: "Koma amashyi hejuru y'umutwe, hanyuma inyuma y'umugongo.",
    clap5: "Koma amashyi buhoro buhoro kugeza bicecetse.",
    back1: "Kanda ibiganza kimwe ku kindi imbere y'igituza, uhagarare.",
    back2: "Egeranya imitsi y'intugu inyuma, hanyuma urekure.",
    back3: "Ibiganza ku mavi, unamye umugongo nk'umusozi, hanyuma uwugorore buhoro.",
    back4: "Fatanya intoki inyuma y'umugongo ufungure igituza.",
    back5: "Unama ugana ku mano, amavi yoroshye, hanyuma uzamuke buhoro.",
  },
};
