import { webkit } from "playwright";
import fs from "node:fs";
const SHOTS = new URL("../shots", import.meta.url).pathname;
const FX = new URL("../.fx", import.meta.url).pathname;
fs.mkdirSync(SHOTS, { recursive: true });
fs.mkdirSync(FX, { recursive: true });
const mock = fs.readFileSync(new URL("../mock.js", import.meta.url), "utf8");
const b = await webkit.launch();
const ctx = await b.newContext({ viewport: { width: 1320, height: 840 } });
await ctx.addInitScript(`localStorage.setItem("nga.theme","dark"); localStorage.setItem("mock.persona","student");`);
await ctx.addInitScript(mock);
const p = await ctx.newPage();
// A fixed school morning (10:00 Kigali) so the agenda never spills over midnight.
await p.clock.install({ time: new Date("2026-10-07T08:00:00Z") });
await p.clock.resume();
const errs = []; p.on("pageerror", (e) => errs.push(e.message));
await p.goto("http://localhost:1420/?overlay=1");
await p.waitForTimeout(300);
await p.evaluate(() => window.__mockEmit("nga://overlay", "tool:my-day"));
await p.waitForSelector(".timeline .tl-item");
await p.waitForTimeout(400);
const r = []; const ok = (n, c, d = "") => r.push(`${c ? "PASS" : "FAIL"} ${n}${d ? " — " + d : ""}`);
ok("query sent as days=7", (await p.evaluate(() => window.__lastQuery)) === "days=7");
ok("now card shows the current lesson", (await p.locator(".nn-card.now strong").textContent()) === "Physics");
ok("next card shows the quiz", (await p.locator(".nn-card:not(.now) strong").textContent()) === "Maths CAT opens");
ok("today lists 4 items, past one dimmed", (await p.locator(".tl-item").count()) === 4 && (await p.locator(".tl-item.past").count()) === 1);
const liveText = await p.locator(".tl-item.live").first().textContent().catch(() => "(none)");
ok("the live item is highlighted", liveText.includes("Physics"), liveText.slice(0, 60));
await p.screenshot({ path: `${SHOTS}/myday-dark.png` });
await p.hover(".tl-item.live");
await p.click('.tl-item.live button:has-text("Open")');
await p.waitForTimeout(200);
ok("Open goes to the MIS page", (await p.evaluate(() => window.__navigated)) === "mis/dashboard");
await p.evaluate(() => window.__mockEmit("nga://overlay", "tool:my-day"));
await p.hover('.tl-item:has-text("Maths CAT")');
await p.click('.tl-item:has-text("Maths CAT") button:has-text("Open")');
await p.waitForTimeout(200);
ok("Task Mentor links open in Task Mentor", (await p.evaluate(() => window.__navigated)) === "taskmentor/quizzes/12");
await p.evaluate(() => window.__mockEmit("nga://overlay", "tool:my-day"));
await p.hover('.tl-item:has-text("Office hours")');
await p.click('.tl-item:has-text("Office hours") button:has-text("Count down")');
await p.waitForSelector(".myday-notice");
ok("Count down creates a timer", (await p.evaluate(() => JSON.parse(localStorage.getItem("mock.state")).timers.length)) === 1);
await p.click('.chip:has-text("Tomorrow")');
const tmr = await p.locator(".tl-item strong").allTextContents();
ok("tomorrow tab shows tomorrow's lesson", tmr.includes("Biology (tomorrow)"), tmr.join(", "));
console.log(r.join("\n")); console.log(errs.length ? "ERRORS " + errs.join(" | ") : "no page errors");
await b.close();
