import { webkit } from "playwright";
import fs from "node:fs";
const SHOTS = new URL("../shots", import.meta.url).pathname;
const FX = new URL("../.fx", import.meta.url).pathname;
fs.mkdirSync(SHOTS, { recursive: true });
fs.mkdirSync(FX, { recursive: true });
const mock = fs.readFileSync(new URL("../mock.js", import.meta.url), "utf8");
const theme = process.argv[2] || "dark";
const r = (n, c, d = "") => console.log(`${c ? "PASS" : "FAIL"} ${n}${d ? " — " + d : ""}`);
const b = await webkit.launch();
const ctx = await b.newContext({ viewport: { width: 1320, height: 900 } });
await ctx.addInitScript(`localStorage.setItem("nga.theme", ${JSON.stringify(theme)});`);
await ctx.addInitScript(mock);
const p = await ctx.newPage(); const errs = []; p.on("pageerror", (e) => errs.push(e.message)); p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
await p.goto("http://localhost:1420/?overlay=1"); await p.waitForTimeout(300);
await p.evaluate(() => window.__mockEmit("nga://overlay", "tool:scanner")); await p.waitForSelector(".scan-start", { timeout: 15000 });
await p.setInputFiles('.scan input[type="file"]', FX + "/text-photo.jpg");
await p.waitForSelector(".scan-stage img"); await p.click('.scan-bar button:has-text("Add page")');
await p.waitForSelector(".ocr", { timeout: 15000 });
const t0 = Date.now();
await p.click('.ocr button:has-text("Read 1 pages")');
await p.waitForSelector(".ocr-text", { timeout: 90000 });
const text = await p.locator(".ocr-text").inputValue();
const words = ["Photosynthesis", "sunlight", "carbon dioxide", "oxygen", "Chlorophyll", "green"];
const found = words.filter((w) => text.toLowerCase().includes(w.toLowerCase()));
r("OCR reads the printed page", found.length >= 5, `${found.length}/6 words in ${Date.now() - t0} ms: ${JSON.stringify(text.slice(0, 160))}`);
await p.screenshot({ path: `${SHOTS}/ocr-${theme}.png` });
await p.click('.ocr button:has-text("Save as .txt")'); await p.waitForTimeout(300);
const saved = (await p.evaluate(() => window.__saved)).at(-1);
r("text saved as .txt", saved.name === "Scan.txt" && Buffer.from(saved.data, "base64").toString().includes("oxygen"), saved.name);
r("no page errors", errs.length === 0, errs.join(" | "));
await b.close();
