import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Find the hidden five-letter word in six tries. Type any five letters and press Enter. Each letter then gets a mark: ● filled circle = right letter in the right place · ○ ring = in the word, but somewhere else · – dash = not in the word. Choose the language of the word. Daily: the same word for the whole school today. Practice: as many words as you like.",
    daily: "Daily",
    practice: "Practice",
    newWord: "New word",
    language: "Word language",
    enter: "Enter",
    erase: "Erase",
    short: "Five letters, please.",
    won: "Well done! Found in {n}.",
    lost: "The word was {word}.",
    tries: "Try {n} of {max}",
    dailyDone: "Come back tomorrow for a new daily word, or practise now.",
    hit: "right place",
    near: "elsewhere in the word",
    miss: "not in the word",
    letter: "{l}: {mark}",
  },
  fr: {
    help: "Trouvez le mot caché de cinq lettres en six essais. Tapez cinq lettres puis Entrée. Chaque lettre reçoit alors une marque : ● rond plein = bonne lettre à la bonne place · ○ anneau = dans le mot, mais ailleurs · – tiret = absente du mot. Les accents ne comptent pas. Choisissez la langue du mot. Du jour : le même mot pour toute l'école aujourd'hui. Entraînement : autant de mots que vous voulez.",
    daily: "Du jour",
    practice: "Entraînement",
    newWord: "Nouveau mot",
    language: "Langue du mot",
    enter: "Entrée",
    erase: "Effacer",
    short: "Cinq lettres, s'il vous plaît.",
    won: "Bravo ! Trouvé en {n}.",
    lost: "Le mot était {word}.",
    tries: "Essai {n} sur {max}",
    dailyDone: "Revenez demain pour un nouveau mot du jour, ou entraînez-vous maintenant.",
    hit: "bonne place",
    near: "ailleurs dans le mot",
    miss: "absente du mot",
    letter: "{l} : {mark}",
  },
  rw: {
    help: "Shaka ijambo ry'inyuguti eshanu ryihishe mu bigeragezo bitandatu. Andika inyuguti eshanu ukande Enter. Buri nyuguti ihabwa ikimenyetso: ● uruziga rwuzuye = inyuguti nyayo ahantu hayo · ○ uruziga rurimo ubusa = iri mu ijambo ariko ahandi · – akarongo = ntiri mu ijambo. Hitamo ururimi rw'ijambo. Iry'uyu munsi: ijambo rimwe ku ishuri ryose uyu munsi. Imyitozo: amagambo menshi uko ubishaka.",
    daily: "Iry'uyu munsi",
    practice: "Imyitozo",
    newWord: "Ijambo rishya",
    language: "Ururimi rw'ijambo",
    enter: "Enter",
    erase: "Siba",
    short: "Inyuguti eshanu, nyamuneka.",
    won: "Ni byiza! Ubibonye mu bigeragezo {n}.",
    lost: "Ijambo ryari {word}.",
    tries: "Igeragezo {n} kuri {max}",
    dailyDone: "Garuka ejo ku ijambo rishya ry'umunsi, cyangwa wimenyereze ubu.",
    hit: "ahantu hayo",
    near: "ahandi mu ijambo",
    miss: "ntiri mu ijambo",
    letter: "{l}: {mark}",
  },
};
