import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Igisoro, Rwanda's board game, for two players at one computer. The board has 4 rows of 8 pits; you own the 2 rows nearest you (your back row and your front row) and only ever sow in them. Standard rules: each player starts with 4 seeds in each pit of the back row (32 seeds). On your turn take all the seeds from one of your pits holding at least 2, and drop them one by one into the following pits, going counter-clockwise around your two rows (back row to your right, front row to your left). If the last seed falls into an empty pit, your turn ends. If it falls into an occupied pit, lift all the seeds there and keep sowing (relay). Capture: if the last seed falls into an occupied pit of your FRONT row and both of the opponent's pits facing it hold seeds, take all those seeds and sow them, starting in the pit where your turn began; then the same rules carry on. A player who cannot move (no pit with 2 or more seeds) loses. The rules in use are shown under the board. Mouse: click one of your pits. Keyboard: arrow keys choose a pit, Enter sows.",
    playerA: "Bottom player",
    playerB: "Top player",
    turn: "{name} to play",
    wins: "{name} wins! The other player cannot move.",
    newGame: "New game",
    rules: "Rules in use",
    hideRules: "Hide rules",
    variant: "Variant: {name}",
    "v.standard": "Standard",
    "v.singles": "Single seeds allowed",
    "v.beginner": "Beginner",
    "r.standard": "Start: 4 seeds in each back-row pit. Move from a pit with 2 or more seeds. Sow counter-clockwise in your own two rows. Last seed in an occupied pit: lift and sow on (relay). Last seed in an occupied front-row pit with both facing opponent pits holding seeds: capture them and sow them starting in the pit where the turn began. No legal move: you lose.",
    "r.singles": "As Standard, but a pit with a single seed may also be moved. You lose only when all your pits are empty.",
    "r.beginner": "Start: 2 seeds in every pit. Move from a pit with 2 or more seeds. No relay: the turn ends where the last seed falls, unless it captures. Capture as in Standard (front row, both facing pits full), sowing the captured seeds from the pit where the turn began. No legal move: you lose.",
    lastMove: "Last move: {name} sowed {n} seeds",
    lastCapture: "Last move: {name} sowed and captured {n} seeds",
    seeds: "{n} seeds",
    pit: "{name}: pit with {n} seeds",
    skip: "Skip animation",
  },
  fr: {
    help: "L'igisoro, jeu de plateau rwandais, pour deux joueurs sur un même ordinateur. Le plateau a 4 rangées de 8 trous ; vous possédez les 2 rangées les plus proches de vous (rangée arrière et rangée avant) et vous ne semez que dans celles-ci. Règles standard : chaque joueur commence avec 4 graines dans chaque trou de sa rangée arrière (32 graines). À votre tour, prenez toutes les graines d'un de vos trous qui en contient au moins 2 et déposez-les une à une dans les trous suivants, dans le sens inverse des aiguilles d'une montre autour de vos deux rangées (rangée arrière vers votre droite, rangée avant vers votre gauche). Si la dernière graine tombe dans un trou vide, votre tour s'arrête. Si elle tombe dans un trou occupé, prenez toutes ses graines et continuez à semer (relais). Capture : si la dernière graine tombe dans un trou occupé de votre rangée AVANT et que les deux trous adverses en face contiennent des graines, prenez-les toutes et semez-les en commençant par le trou d'où votre tour est parti ; ensuite les mêmes règles continuent. Un joueur qui ne peut pas jouer (aucun trou avec 2 graines ou plus) perd. Les règles en vigueur sont affichées sous le plateau. Souris : cliquez un de vos trous. Clavier : les flèches choisissent un trou, Entrée sème.",
    playerA: "Joueur du bas",
    playerB: "Joueur du haut",
    turn: "À {name} de jouer",
    wins: "{name} gagne ! L'autre joueur ne peut plus jouer.",
    newGame: "Nouvelle partie",
    rules: "Règles en vigueur",
    hideRules: "Masquer les règles",
    variant: "Variante : {name}",
    "v.standard": "Standard",
    "v.singles": "Graine seule permise",
    "v.beginner": "Débutant",
    "r.standard": "Départ : 4 graines dans chaque trou de la rangée arrière. On joue un trou d'au moins 2 graines. On sème dans le sens inverse des aiguilles d'une montre dans ses deux rangées. Dernière graine dans un trou occupé : on reprend tout et on continue (relais). Dernière graine dans un trou occupé de la rangée avant, et les deux trous adverses en face sont garnis : on les capture et on les sème en commençant par le trou de départ du tour. Plus de coup possible : on perd.",
    "r.singles": "Comme Standard, mais un trou d'une seule graine peut aussi être joué. On ne perd que lorsque tous ses trous sont vides.",
    "r.beginner": "Départ : 2 graines dans chaque trou. On joue un trou d'au moins 2 graines. Pas de relais : le tour s'arrête où tombe la dernière graine, sauf capture. Capture comme en Standard (rangée avant, deux trous en face garnis), en semant les graines capturées depuis le trou de départ du tour. Plus de coup possible : on perd.",
    lastMove: "Dernier coup : {name} a semé {n} graines",
    lastCapture: "Dernier coup : {name} a semé et capturé {n} graines",
    seeds: "{n} graines",
    pit: "{name} : trou de {n} graines",
    skip: "Passer l'animation",
  },
  rw: {
    help: "Igisoro, umukino w'ikibaho wo mu Rwanda, ukinwa n'abantu babiri kuri mudasobwa imwe. Ikibaho gifite imirongo 4 y'imyobo 8; ufite imirongo 2 ikwegereye (umurongo w'inyuma n'uw'imbere) kandi utera mu yawe gusa. Amategeko asanzwe: buri mukinnyi atangira afite intete 4 muri buri mwobo w'umurongo w'inyuma (intete 32). Iyo ari wowe ukina, fata intete zose ziri mu mwobo wawe ufite nibura 2, uzitere imwe imwe mu myobo ikurikiraho, uzenguruka imirongo yawe yombi mu cyerekezo kinyuranye n'icy'inshinge z'isaha (umurongo w'inyuma ujya iburyo bwawe, uw'imbere ujya ibumoso bwawe). Iyo intete ya nyuma iguye mu mwobo urimo ubusa, igihe cyawe kirarangiye. Iyo iguye mu mwobo urimo intete, zifate zose ukomeze gutera. Kurya: iyo intete ya nyuma iguye mu mwobo urimo intete wo ku murongo wawe w'IMBERE, kandi imyobo yombi y'uwo muhanganye iteganye nawo irimo intete, zirye zose uzitere uhereye ku mwobo watangiriyeho; nyuma amategeko amwe arakomeza. Umukinnyi utagishoboye gukina (nta mwobo ufite intete 2 cyangwa zirenga) aba atsinzwe. Amategeko akoreshwa agaragara munsi y'ikibaho. Imbeba: kanda ku mwobo wawe. Mudasobwa: imyambi ihitamo umwobo, Enter iratera.",
    playerA: "Umukinnyi wo hasi",
    playerB: "Umukinnyi wo hejuru",
    turn: "{name} arakina",
    wins: "{name} aratsinze! Undi ntagishoboye gukina.",
    newGame: "Umukino mushya",
    rules: "Amategeko akoreshwa",
    hideRules: "Hisha amategeko",
    variant: "Uburyo: {name}",
    "v.standard": "Busanzwe",
    "v.singles": "Intete imwe iremewe",
    "v.beginner": "Abatangizi",
    "r.standard": "Gutangira: intete 4 muri buri mwobo w'umurongo w'inyuma. Ukina umwobo ufite nibura intete 2. Utera mu cyerekezo kinyuranye n'icy'inshinge z'isaha mu mirongo yawe ibiri. Intete ya nyuma mu mwobo urimo intete: uzifata ukomeza gutera. Intete ya nyuma mu mwobo urimo intete wo ku murongo w'imbere, imyobo yombi y'uwo muhanganye iteganye nawo irimo intete: urazirya ukazitera uhereye ku mwobo watangiriyeho. Nta mukino ushoboka: uratsinzwe.",
    "r.singles": "Nk'uburyo busanzwe, ariko umwobo ufite intete imwe na wo ushobora gukinwa. Utsindwa gusa iyo imyobo yawe yose irimo ubusa.",
    "r.beginner": "Gutangira: intete 2 muri buri mwobo. Ukina umwobo ufite nibura intete 2. Nta gukomeza: igihe kirangira aho intete ya nyuma iguye, keretse iriye. Kurya ni nk'uburyo busanzwe (umurongo w'imbere, imyobo yombi iteganye yuzuye), intete zariwe ziterwa uhereye ku mwobo watangiriyeho. Nta mukino ushoboka: uratsinzwe.",
    lastMove: "Umukino uheruka: {name} yateye intete {n}",
    lastCapture: "Umukino uheruka: {name} yateye arya intete {n}",
    seeds: "Intete {n}",
    pit: "{name}: umwobo ufite intete {n}",
    skip: "Simbuka igikorwa",
  },
};
