import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Take turns dropping a disc into one of the 7 columns; it falls to the lowest free space. Line up four of your discs across, up and down or on a slant to win. A full board with no line is a draw. Mouse: click a column. Keyboard: ← → choose a column, Enter, Space or ↓ drops. Play with a friend on this computer, or against the computer (Easy or Normal).",
    two: "2 players",
    easy: "Computer: easy",
    normal: "Computer: normal",
    p1: "Blue",
    p2: "Gold",
    you: "You",
    computer: "Computer",
    turn: "{name} to play",
    thinking: "The computer is thinking…",
    wins: "{name} wins!",
    youWin: "You win!",
    computerWins: "The computer wins this time.",
    draw: "A draw: the board is full.",
    newGame: "New game",
    column: "Column {n}",
  },
  fr: {
    help: "Chacun à son tour lâche un jeton dans l'une des 7 colonnes ; il tombe dans la case libre la plus basse. Alignez quatre de vos jetons à l'horizontale, à la verticale ou en diagonale pour gagner. Grille pleine sans alignement : match nul. Souris : cliquez une colonne. Clavier : ← → choisissent la colonne, Entrée, Espace ou ↓ lâche le jeton. Jouez à deux sur cet ordinateur, ou contre l'ordinateur (Facile ou Normal).",
    two: "2 joueurs",
    easy: "Ordinateur : facile",
    normal: "Ordinateur : normal",
    p1: "Bleu",
    p2: "Or",
    you: "Vous",
    computer: "Ordinateur",
    turn: "À {name} de jouer",
    thinking: "L'ordinateur réfléchit…",
    wins: "{name} gagne !",
    youWin: "Vous avez gagné !",
    computerWins: "L'ordinateur gagne cette fois.",
    draw: "Match nul : la grille est pleine.",
    newGame: "Nouvelle partie",
    column: "Colonne {n}",
  },
  rw: {
    help: "Musimburana mushyira igiceri mu nkingi imwe muri 7; kimanuka kikagera ahantu hasigaye hasi cyane. Huza ibiceri byawe bine ku murongo utambitse, uhagaze cyangwa uberamye kugira ngo utsinde. Iyo ikibaho cyuzuye nta murongo, ni inganya. Imbeba: kanda ku nkingi. Mudasobwa: ← → hitamo inkingi, Enter, Space cyangwa ↓ birashyira. Kina na mugenzi wawe kuri iyi mudasobwa, cyangwa ukine na mudasobwa (Byoroshye cyangwa Bisanzwe).",
    two: "Abakinnyi 2",
    easy: "Mudasobwa: byoroshye",
    normal: "Mudasobwa: bisanzwe",
    p1: "Ubururu",
    p2: "Zahabu",
    you: "Wowe",
    computer: "Mudasobwa",
    turn: "{name} arakina",
    thinking: "Mudasobwa iratekereza…",
    wins: "{name} aratsinze!",
    youWin: "Waratsinze!",
    computerWins: "Mudasobwa itsinze ubu.",
    draw: "Inganya: ikibaho cyuzuye.",
    newGame: "Umukino mushya",
    column: "Inkingi {n}",
  },
};
