import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Steer the snake with the arrow keys or W A S D (or the buttons). Eat the food to grow longer; the snake speeds up a little as it grows. Don't run into your own body. With gentle walls on, the snake passes through the edges and comes out on the other side; with them off, the edges stop the run. P pauses and resumes. Press any arrow to start.",
    length: "Length",
    best: "Best",
    start: "Press an arrow key (or a button) to start",
    paused: "Paused. Press P or an arrow to go on.",
    over: "Nice run! Length {n}",
    full: "You filled the whole garden! Length {n}",
    walls: "Gentle walls: pass through",
    pause: "Pause",
    resume: "Resume",
    newGame: "New game",
    up: "Up", down: "Down", left: "Left", right: "Right",
  },
  fr: {
    help: "Dirigez le serpent avec les flèches ou W A S D (ou les boutons). Mangez la nourriture pour grandir ; le serpent accélère un peu en grandissant. Ne heurtez pas votre propre corps. Avec les bords doux, le serpent traverse les bords et ressort de l'autre côté ; sans eux, les bords arrêtent la partie. P met en pause et reprend. Appuyez sur une flèche pour commencer.",
    length: "Longueur",
    best: "Record",
    start: "Appuyez sur une flèche (ou un bouton) pour commencer",
    paused: "En pause. Appuyez sur P ou une flèche pour continuer.",
    over: "Belle partie ! Longueur {n}",
    full: "Vous avez rempli tout le jardin ! Longueur {n}",
    walls: "Bords doux : on les traverse",
    pause: "Pause",
    resume: "Reprendre",
    newGame: "Nouvelle partie",
    up: "Haut", down: "Bas", left: "Gauche", right: "Droite",
  },
  rw: {
    help: "Yobora inzoka ukoresheje utumenyetso tw'imyambi cyangwa W A S D (cyangwa buto). Rya ibiryo kugira ngo ukure; inzoka yihuta gato uko ikura. Ntukagonge umubiri wawe. Iyo inkuta zoroshye zifunguye, inzoka inyura ku mpera igasohokera ku rundi ruhande; iyo zifunze, impera zihagarika umukino. P irahagarika ikanakomeza. Kanda umwambi kugira ngo utangire.",
    length: "Uburebure",
    best: "Agahigo",
    start: "Kanda umwambi (cyangwa buto) kugira ngo utangire",
    paused: "Wahagaze. Kanda P cyangwa umwambi ukomeze.",
    over: "Wakinnye neza! Uburebure {n}",
    full: "Wujuje umurima wose! Uburebure {n}",
    walls: "Inkuta zoroshye: urazinyuramo",
    pause: "Hagarika",
    resume: "Komeza",
    newGame: "Umukino mushya",
    up: "Hejuru", down: "Hasi", left: "Ibumoso", right: "Iburyo",
  },
};
