import type { GameStrings } from "../types";

export const strings: GameStrings = {
  en: {
    help: "Pick your level (S1–S6) and press Start. You have 60 seconds: type each answer and press Enter. A wrong answer shows the right one for a moment and the next question comes. Your score is the number of correct answers. S1–S2: tables, adding, subtracting · S3–S4: negatives, squares, percentages, mixed operations · S5–S6: powers, square roots, equations, log base 10.",
    level: "Level",
    start: "Start",
    again: "New round",
    score: "Correct",
    best: "Best",
    time: "Time",
    answer: "Your answer",
    submit: "Enter",
    right: "Right!",
    wrong: "{q} = {a}",
    over: "Time! {n} correct out of {m}.",
    of: "of",
    ready: "60 seconds. Ready?",
  },
  fr: {
    help: "Choisissez votre niveau (S1–S6) et appuyez sur Commencer. Vous avez 60 secondes : tapez chaque réponse puis Entrée. Une mauvaise réponse affiche un instant la bonne, puis la question suivante arrive. Votre score est le nombre de bonnes réponses. S1–S2 : tables, additions, soustractions · S3–S4 : nombres négatifs, carrés, pourcentages, opérations mélangées · S5–S6 : puissances, racines carrées, équations, logarithme décimal.",
    level: "Niveau",
    start: "Commencer",
    again: "Nouvelle manche",
    score: "Justes",
    best: "Record",
    time: "Temps",
    answer: "Votre réponse",
    submit: "Entrée",
    right: "Juste !",
    wrong: "{q} = {a}",
    over: "Temps écoulé ! {n} justes sur {m}.",
    of: "de",
    ready: "60 secondes. Prêt ?",
  },
  rw: {
    help: "Hitamo urwego rwawe (S1–S6) hanyuma ukande Tangira. Ufite amasegonda 60: andika igisubizo cya buri kibazo ukande Enter. Igisubizo kitari cyo kigaragaza igisubizo nyacyo akanya gato, hanyuma ikibazo gikurikira kikaza. Amanota yawe ni umubare w'ibisubizo by'ukuri. S1–S2: gukuba, guteranya, gukuramo · S3–S4: imibare iri munsi ya zeru, kare, ijanisha, ibikorwa bivanze · S5–S6: ibipimo (puissances), imizi ya kare, ingereranyo, log fatizo 10.",
    level: "Urwego",
    start: "Tangira",
    again: "Icyiciro gishya",
    score: "Ukuri",
    best: "Agahigo",
    time: "Igihe",
    answer: "Igisubizo cyawe",
    submit: "Enter",
    right: "Ni byo!",
    wrong: "{q} = {a}",
    over: "Igihe kirarangiye! Ibisubizo {n} by'ukuri kuri {m}.",
    of: "bya",
    ready: "Amasegonda 60. Witeguye?",
  },
};
